# Numpy 101

The goal of this challenge is to get familiar with the Numpy library, manipulate multidimensional arrays and apply some linear algebra operations without using `for` loops.

💡 Do not forget to keep the [Numpy Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf) close during this challenge.

In [5]:
import numpy as np # Run this cell!

---

**Q1** - Create a null vector (i.e. with only zeros `0`) of size 10 and assign it to a variable named `ten_zeros`. 

It should look like this:

```
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.zeros.html"><code>numpy.zeros</code></a></p>
</details>

In [59]:
# your code here
ten_zeros = np.zeros(10)
ten_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

---

**Q2** - Create a vector with values from 5 to 10 and assign it to a variable named `five_to_ten`.

It should look like this:

```
array([ 5,  6,  7,  8,  9, 10])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.arange.html"><code>numpy.arange</code></a></p>
</details>

In [60]:
# your code here
from_five = np.arange(5, 11)
from_five

array([ 5,  6,  7,  8,  9, 10])

---

**Q3** - Create the following matrix as a NumPy `ndarray` and assign it to a variable named `A`:

$
A = 
\begin{pmatrix}
5 & 9 & 7\\
1 & 0 & 3
\end{pmatrix}
$

<br>
<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.array.html"><code>numpy.array</code></a></p>
    <p>Checkout more about the relationship between<a href="https://stackoverflow.com/questions/15879315/what-is-the-difference-between-ndarray-and-array-in-numpy"><code>numpy.array and numpy.ndarray</code></a></p>
</details>

In [15]:
# your code here
A = np.array([[5,9,7],[1,0,3]])
A

array([[5, 9, 7],
       [1, 0, 3]])

---
**Q4** - Create the following matrix without using the `np.array()` constructor and assign it to a variable named `B`:

$
B = 
\begin{pmatrix}
1 & 1\\
1 & 1
\end{pmatrix}
$

In [62]:
# your code here
B = np.ones((2,2),dtype= int)
B

array([[1, 1],
       [1, 1]])

---

**Q5** - Create a vector of 20 elements evenly spaced between `-1` and `1` and assign it to a variable named `lin_twenty`.

It should look like this:

```
array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.linspace.html"><code>numpy.linspace</code></a></p>
</details>

In [55]:
# your code here
lin_twenty = np.linspace(-1, 1, 20)

lin_twenty

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

---

**Q6** - Create a 3x3 identity matrix and assign it to a variable named `C`:

$
C = 
\begin{pmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{pmatrix}
$

<br>

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.eye.html"><code>numpy.eye</code></a></p>
</details>

In [80]:
# your code here
C = np.eye(3,dtype="int")
C

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

---

**Q7** - Create the following `ndarray` and assign it to a variable named `D`:  

$
D = 
\begin{pmatrix}
2 & 9 & 7 & 3 & 1 & 5
\end{pmatrix}
$

Reshape `D` into a 2x3 matrix and assign it to a variable named `E`:

$
E = 
\begin{pmatrix}
2 & 9 & 7\\
3 & 1 & 5
\end{pmatrix}
$

<br>

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.reshape.html"><code>numpy.reshape</code></a></p>
</details>

In [78]:
# your code here
D = np.array([2, 9, 7, 3, 1, 5])
E = D.reshape(2,3)
E

array([[2, 9, 7],
       [3, 1, 5]])

---

**Q8** - Create a 8x8 checkboard matrix and assign it to a variable named `F`:

$
F = 
\begin{pmatrix}
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
\end{pmatrix}
$

<br>

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.tile.html"><code>numpy.tile</code></a></p>
</details>

In [83]:
# your code here
F = np.array([[1, 0],[0, 1]])
F = np.tile(F, (4,4))

In [85]:
F

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

---

**Q9**: Select the second column of this `ndarray` `G`, reshape it as an `ndarray` of 4 lines and 1 column and assign it to a variable named `reshaped_G`:

$
reshaped\_G = 
\begin{pmatrix}
0.?\\
0.?\\
0.?\\
0.?\\
\end{pmatrix}
$

In [72]:
G = np.random.random((4, 5))
print(G)

[[0.28595347 0.04668998 0.34557289 0.38454543 0.35222156]
 [0.73847148 0.70462684 0.12165309 0.04642913 0.57216704]
 [0.36822678 0.94238144 0.31595438 0.38647277 0.05688028]
 [0.40347176 0.91943974 0.8407157  0.78243248 0.12054858]]


In [76]:
# your code here
reshaped_G = G[:,1].reshape(4,1)
reshaped_G

array([[0.04668998],
       [0.70462684],
       [0.94238144],
       [0.91943974]])

---

**Q10** - Compute the sum of matrixes `H` and `I` and store the result into a variable `gh_sum`:

$
H = 
\begin{pmatrix}
0 & 4\\
-4 & -3\\
1 & 1
\end{pmatrix}
$

$
I =
\begin{pmatrix}
0 & 1\\
1 & -1\\
2 & 3
\end{pmatrix}
$

$
H + I = ?
$


In [53]:
# your code here
G = np.array([[0,4],[-4,-3],[1,1]])
H = np.array([[0,1],[1,-1],[2,3]])
gh_sum = (G+H)
gh_sum

array([[ 0,  5],
       [-3, -4],
       [ 3,  4]])

## Check your code!

Run the cell below to check your code:

In [86]:
from nbresult import ChallengeResult

result = ChallengeResult('numpy',
    ten=ten_zeros,
    from_five=five_to_ten,
    A=A,
    B=B,
    lin_twenty=lin_twenty,
    C=C,
    E=E,
    F=F,
    reshaped_G=reshaped_G,
    hi_sum=hi_sum
)
result.write()
print(result.check())

============================= test session starts ==============================
platform darwin -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /Users/selmalopez/.pyenv/versions/lewagon_current/bin/python3
cachedir: .pytest_cache
rootdir: /Users/selmalopez/code/selmalopez/data-challenges/02-Data-Toolkit/01-Data-Analysis/01-Numpy
plugins: dash-2.0.0, anyio-3.3.2
collecting ... collected 5 items

tests/test_numpy.py::TestNumpy::test_advanced_matrixes_manipulation PASSED [ 20%]
tests/test_numpy.py::TestNumpy::test_linear_twenty_vector_creation PASSED [ 40%]
tests/test_numpy.py::TestNumpy::test_matrixes_creation_and_reshaping PASSED [ 60%]
tests/test_numpy.py::TestNumpy::test_ndarrays_creation PASSED            [ 80%]
tests/test_numpy.py::TestNumpy::test_vectors_creation PASSED             [100%]

============================== 5 passed in 0.14s ===============================


💯 You can commit your code:

git add tests/numpy.pickle

git commit -m 'Completed numpy step'

git p